# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: c3po
  host: localhost
  port: 5432

development:
  <<: *default
  database: airbnb_development



test:
  <<: *default
  database: airbnb_test


#
production:
  <<: *default
  database: airbnb_production
  username: airbnb
  password: <%= ENV["AIRBNB_DATABASE_PASSWORD"] %>





# psql -U postgres


# CREATE DATABASE airbnb_development;
# CREATE DATABASE airbnb_test;
# CREATE DATABASE airbnb_production;

# GRANT ALL PRIVILEGES ON DATABASE airbnb_development TO postgres;
# GRANT ALL PRIVILEGES ON DATABASE airbnb_test TO postgres;
# GRANT ALL PRIVILEGES ON DATABASE airbnb_production TO postgres;

# psql -U postgres -h localhost -d airbnb_development

# \list

#\dt

# \q


